name: 'Troubleshooting'

on:
  workflow_dispatch:
    inputs:
      displayNameOfSecrets:
        description: Display the name (not the value) of secrets available to the repository
        type: boolean
        default: false

permissions:
  actions: read
  contents: read

defaults:
  run:
    shell: pwsh

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  Troubleshooting:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          lfs: true

      - name: Troubleshooting
        uses: freddydk/AL-Go/Actions/Troubleshooting@trustedSigning
        with:
          shell: pwsh
          gitHubSecrets: ${{ toJson(secrets) }}
          displayNameOfSecrets: ${{ github.event.inputs.displayNameOfSecrets }}
